/** 查询结果列名 → 中文表头。未收录的英文名原样展示；已含汉字的不改。 */

const COLUMN_LABELS: Record<string, string> = {
  exam_name: "考试",
  exam: "考试",
  ksmc: "考试",
  batch_name: "考试批次",
  paper_name: "试卷",
  exam_time: "考试时间",
  district: "区县",
  dq: "区县",
  qx: "区县",
  line_name: "分数线",
  line_code: "分数线代码",
  threshold: "分数线",
  track: "选科",
  xkkm: "选科",
  xkfx: "选科方向",
  reached_count: "达线人数",
  candidates: "参考人数",
  reach_rate: "达线率",
  school_name: "学校",
  school_id: "学校",
  xx: "学校",
  xxlb: "校类",
  class_name: "班级",
  class: "班级",
  bj: "班级",
  student_id: "学号",
  anon_stu_id: "学号",
  student_name: "姓名",
  xm: "姓名",
  xsxz: "学生性质",
  subject: "科目",
  subject_name: "科目",
  score: "分数",
  exam_score: "满分",
  full_score: "满分",
  avg_score: "均分",
  avg: "均分",
  n: "人数",
  cnt: "人数",
  count: "人数",
  total: "合计",
  zf6m: "六门总分",
  zf4m: "四门总分",
  zf3m: "三门总分",
  yw: "语文",
  sx: "数学",
  yy: "英语",
  wl: "物理",
  hx: "化学",
  sw: "生物",
  zz: "政治",
  ls: "历史",
  dl: "地理",
  hxzh: "化学转换分",
  swzh: "生物转换分",
  zzzh: "政治转换分",
  dlzh: "地理转换分",
  question_no: "题号",
  question_score: "题目满分",
  item_score: "小题得分",
  question_type: "题型",
  knowledge_name: "知识点",
  ability_level: "能力层级",
  score_rate: "得分率",
};

export function labelColumn(name: string): string {
  const raw = (name || "").trim();
  if (!raw) return raw;
  if (/[\u4e00-\u9fff]/.test(raw)) return raw;
  const key = (raw.split(".").pop() || raw).toLowerCase();
  return COLUMN_LABELS[key] || raw;
}
